VIP Architeture
VitorCosta98/MinionMovies pull request #15
Opened 2020-05-26 17:43 UTC by VitorCosta98

## Description

This branch consists of adapting the project to the VIP architecture.

### What has changed.

The main and details screens were divided into: View, Interactor, Presenter, Worker and DataProvider. In which specific functions were delegated for each one, dividing the work and facilitating the reading, the implementation of tests and the changes in the project.

2020-05-26 17:52 UTC, giovanepossebon commented on MinionMovies/DetailsView/DetailsViewPresenter.swift
> +        createStars(with: item.metascore!)
evita usar esse monte de force unwrap, pq se algum deles tiver vazio, teu app quebra

2020-05-26 17:53 UTC, giovanepossebon commented on MinionMovies/HomeView/HomeViewInteractor.swift
> +        for item in items! {
se items for vazio, vai quebrar

2020-05-26 17:55 UTC, giovanepossebon commented on MinionMovies/DetailsView/DetailsViewDataProvider.swift
> +    func getSpecificItem(with id: String) -> MovieDB
esse nome de funcao ficou estranho, quem sabe getMovie(with id: String) -> MovieDB?

2020-05-26 17:56 UTC, giovanepossebon commented on MinionMovies/DetailsView/DetailsViewDataProvider.swift
> +    func check(item: String) -> Bool
delete(item: String)... o que é item do tipo string? pra mim que to lendo não sei o que eu to deletando com um string chamado item

2020-05-26 17:58 UTC, giovanepossebon commented on MinionMovies/DetailsView/DetailsViewInteractor.swift
> +    }
ta estranho isso... quando tu seta um id, ele seta um movie? pq?

2020-05-26 17:59 UTC, giovanepossebon commented on MinionMovies/DetailsView/DetailsViewWorker.swift
> +    func check(item: String) -> Bool
o que é item do tipo string?

2020-05-26 18:12 UTC, giovanepossebon commented on MinionMovies/HomeView/HomeViewInteractor.swift
> +    func searching(string: String) {
variavel com nome de string? nah nah nah haha

2020-05-27 14:45 UTC, Raafas commented on MinionMovies/AppDelegate.swift
> +        interactor.worker?.dataProvider = HomeViewDataProvider(config: .basic)
Porque tu não inicializa teu Worker com o data provider ou põe isso no init?

2020-05-27 14:46 UTC, Raafas commented on MinionMovies/DBManager.swift
> +    func check(objectId: String, type: Object.Type) -> Bool
`check` what?

2020-05-27 14:47 UTC, Raafas commented on MinionMovies/DetailsView/DetailsViewController.swift
> +        interactor?.buttonFavMovieWasClicked()
`buttonFavMovieWasTapped()` não tem click, é toque

2020-05-27 14:49 UTC, VitorCosta98 commented on MinionMovies/DBManager.swift
> +    func check(objectId: String, type: Object.Type) -> Bool
Pela assinatura do método, tá confuso de saber o que ele faz?

2020-05-27 14:49 UTC, Raafas commented on MinionMovies/DetailsView/DetailsViewDataProvider.swift
> +    func getMovie(with id: String) -> MovieDB
fetchMovie

2020-05-27 17:23 UTC, Raafas requested changes

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/DBManager.swift
> +        return objects.first!
Evita o uso de force

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/DetailsView/DetailsViewInteractor.swift
> +        presenter?.showTrailer(urlString: checkedMovie.trailer!)
evita o force

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/DBManager.swift
> +    func check(objectId: String, type: Object.Type) -> Bool
ele checa alguma coisa, n da pra saber o que

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/DBManager.swift
> +    func check(objectId: String, type: Object.Type) -> Bool {
tu ja tem uma função que pega o objeto do banco, nao precisa dessa

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/DBManager.swift
> +    func retrieveSpecificItem(objectId: String, type: Object.Type) -> Object {
retrieveItem ou fetchItem

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/DetailsView/DetailsViewDataProvider.swift
> +        return dbManager.retrieveSpecificItem(objectId: id, type: MovieDB.self) as! MovieDB
force aqui tbm

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/DetailsView/DetailsViewPresenter.swift
> +        while i <= 5 {
force aqui tbm

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/DetailsView/DetailsViewWorker.swift
> +    func checkMovie(with id: String) -> Bool
Não diz o que checa aqui tbm e se for pra checar sem existe tu pode usar a função de fetch

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/HomeView/HomeViewController.swift
> +        movieDetail.id = movies![indexPath.row].id
force aqui tbm

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/HomeView/HomeViewInteractor.swift
> +    func searching(title: String)
search

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/HomeView/HomeViewInteractor.swift
> +    var items: [MovieDB]?
pelo q to vendo aqui, essa lista nao ta sendo utilizada

2020-05-27 17:23 UTC, Raafas commented on MinionMovies/HomeView/HomeViewInteractor.swift
> +    var items: [MovieDB]?
o teu presenter pode pegar os valores daqui quando for notificado

2020-06-02 18:24 UTC, Raafas requested changes

2020-06-02 18:24 UTC, Raafas commented on MinionMovies/DBManager.swift
> +    var config = Realm.Configuration()
Essa configuração nao ta sendo usada em lugar nenhum

2020-06-02 18:46 UTC, Raafas approved these changes

2020-06-03 18:28 UTC, merged